# Generated by Django 4.2.7 on 2023-12-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='user_id в Telegram'),
        ),
    ]
