# Generated by Django 4.2.7 on 2023-12-05 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='действие')),
                ('time_habit', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='время на получение вознаграждения, сек.')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'вознаграждение',
                'verbose_name_plural': 'вознаграждения',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место')),
                ('time', models.TimeField(verbose_name='время')),
                ('action', models.CharField(max_length=100, verbose_name='действие')),
                ('is_enjoy_habit', models.BooleanField(blank=True, default=False, null=True, verbose_name='признак приятной привычки')),
                ('periodicity', models.CharField(choices=[('once_2_hours', '1 раз в 2 часа'), ('three_times_day', '3 раза в день'), ('once_day', '1 раз в день'), ('twice_week', '2 раза в неделю'), ('once_week', '1 раз в неделю')], default='once_day', max_length=25, verbose_name='периодичность')),
                ('time_habit', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='время на выполнение привычки, сек.')),
                ('is_public', models.BooleanField(blank=True, default=False, null=True, verbose_name='признак публичной привычки')),
                ('link_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='связанная привычка')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.reward', verbose_name='вознаграждение')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
                'ordering': ('id',),
            },
        ),
    ]
