# Generated by Django 4.2.7 on 2023-12-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_is_enjoy_habit_alter_habit_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='habit',
            name='last_reminder',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последнего напоминания'),
        ),
        migrations.AddField(
            model_name='habit',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='дата обновления'),
        ),
    ]
