# Generated by Django 4.2.7 on 2023-12-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_create_date_habit_last_reminder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(choices=[('once_day', '1 раз в день'), ('twice_week', '2 раза в неделю'), ('once_week', '1 раз в неделю')], default='once_day', max_length=25, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_habit',
            field=models.PositiveSmallIntegerField(default=120, verbose_name='время на выполнение привычки, сек.'),
        ),
    ]
